### ISSUE TITLE
Indicator menu items grayed out - Elementary OS

### ISSUE THREAD

**Issue by k4r7u** [dlech/Keebuntu#19]
![eos keepass](https://cloud.githubusercontent.com/assets/8782287/5245793/cdf9f122-7960-11e4-903e-44e14301f58b.JPG)
After installing keepass2-plugin-application-indicator, the indicator starts when starting Keepass2.
Unfortunately all menu items of the application indicator are grayed out.
Starting Keepass2 via console doesn't show any errors, except from the usual ones (SendMesssage (0, .....))

Any help would be greatly appreciated.

System: Elementary OS Luna
Kernel: 3.2.0-73-generic
Keepass2: 2.18
AppIndicator: 0.3.2.0

**Comment by dlech** [comment]
closing due to no response.
