### ISSUE TITLE
Ubuntu 15.04

### ISSUE THREAD

**Issue by sigboe** [dlech/Keebuntu#22]
Please package for Ubuntu 15.04.
I am unable to find instructions on how to compile this my self.

**Comment by dlech** [comment]
There should be packages in the PPA already. Or are you saying that the existing packages are broken?

**Comment by sigboe** [comment]
I have installed keepass2-plugin-launcher
but there are no plugins in KeePass2 and no right click functionality.

**Comment by dlech** [comment]
This has been published in ppa:dlech/keepass2-plugins-beta
