### ISSUE TITLE
keepass2-plugin-application-indicator not installable in ubuntu 15.04

### ISSUE THREAD

**Issue by vmeurisse** [dlech/Keebuntu#23]
Hi,

keepass2-plugin-application-indicator depend on libmagickwand5 through keepass2-plugin-libimagemagick.
Unfortunately,  libmagickwand5 doesn't exist anymore in 15.04: http://packages.ubuntu.com/fr/utopic/libmagickwand5

Can you please update the dependency to a newer version?

**Comment by dlech** [comment]
Hmm... They must have just removed it. It was working in #22

**Comment by dlech** [comment]
I've updated the libmagicwand dependency and pushed a new package to ppa:dlech/keepass2-plugins-beta (0.5.6.1). Give it a try and close this issue if it is fixed.

**Comment by dlech** [comment]
@kaptoxic, this will break your AUR package. You need to update the sed line for libMagickWand.

**Comment by dlech** [comment]
https://github.com/dlech/Keebuntu/commit/e1a2f3fc89be39b30e6a035da957f4e9904beab9

**Comment by kaptoxic** [comment]
Does [this](https://github.com/kaptoxic/aur-packages/blob/tentative/keebuntu/PKGBUILD#L38) look right?

**Comment by dlech** [comment]
Yes, that looks correct.

**Comment by vmeurisse** [comment]
I've just updated and it is working fine.

Btw, you can add KDE to the list of your tested desktops for Application Indicator. Kubuntu user will love it.

**Comment by dlech** [comment]
> you can add KDE to the list of your tested desktops for Application Indicator

Done.
