### ISSUE TITLE
keepass2-plugin-application-indicator should use Unity icon on Elementary OS Freya

### ISSUE THREAD

**Issue by soissons** [dlech/Keebuntu#26]
The plugin currently uses the blue icon
![keepass indicator elementary os](https://cloud.githubusercontent.com/assets/1542063/7760633/99669020-001d-11e5-8a12-f5db33713475.png)

it would be nice if it would use the same one as on Unity.

![keepass indicator unity](https://cloud.githubusercontent.com/assets/1542063/7760666/f75a5220-001d-11e5-850a-1843f8312310.png)

**Comment by dlech** [comment]
I use Freya too, so this is something that I have been wanting to do. I just haven't dug deep enough to figure out where the icon needs to be installed to make it work.

**Comment by dlech** [comment]
This is fixed in `0.5.5trusty1` available in the beta ppa.
