### ISSUE TITLE
Ubuntu Gnome 15.04 dependency problems

### ISSUE THREAD

**Issue by firtek** [dlech/Keebuntu#27]
Hi,

When adding your repository to Ubuntu Gnome 15.04 and trying to install indicator I get the following error:
```
The following packages have unmet dependencies.
 keepass2-plugin-application-indicator : Depends: keepass2-plugin-libimagemagick (= 0.2.7+0.4.8) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by dlech** [comment]
What is you entry in `/etc/apt/sources.list`? I thought I had this sorted, so make sure you are targeting vivid and not an older distro.

**Comment by firtek** [comment]
It is:
dlech-ubuntu-keepass2-plugins-vivid.list

**Comment by dlech** [comment]
Maybe try the beta repo instead. 

    deb http://ppa.launchpad.net/dlech/keepass2-plugins-beta/ubuntu vivid main

**Comment by dlech** [comment]
Actually, it is OK to have both

    deb http://ppa.launchpad.net/dlech/keepass2-plugins/ubuntu vivid main
    deb http://ppa.launchpad.net/dlech/keepass2-plugins-beta/ubuntu vivid main

**Comment by dlech** [comment]
and now that I am thinking of it, better to install with `sudo apt-add ppa:dlech/keepass2-plugins-beta`

**Comment by firtek** [comment]
It works with beta. Thanks :)

There is also this interesting behaviour when minimizing to tray, like it gets minimized then appears again and then gets minimized again. Happens to me both on Cinnamon 2.6 and Gnome 3.14 (gnome ubuntu 15.04).

**Comment by dlech** [comment]
> There is also this interesting behaviour when minimizing to tray, like it gets minimized then appears again and then gets minimized again.

Yes, this is a side effect of working around other bugs in Mono.
