### ISSUE TITLE
Too large icon in Gnome message tray

### ISSUE THREAD

**Issue by firtek** [dlech/Keebuntu#28]
Hi, 

In Gnome DE (Gnome Ubuntu 15.04) icon for keepass is too large (in message tray) compared to the other icons, cf. the attached image. 
![notification_bar](https://cloud.githubusercontent.com/assets/6161338/8765010/fc9869d0-2df8-11e5-8a09-de45d4bf24be.png)

Regards.

**Comment by dlech** [comment]
I don't recognize the taskbar. Is this "GNOME", "GNOME Classic" or "GNOME Fallback"? Are you using a custom theme? Do you have a high-dpi display?

**Comment by firtek** [comment]
It is default on Gnome, check the bigger picture. I think proper name is message tray and gnome pushes all icons down. It is sort of high-dpi i.e. 1920 on 14" desktop, unfortunately gnome hi-dpi only supports whole number scaling i.e. 2 times (which is too much for me) so I have no scaling turned on.

![screenshot from 2015-07-19 21 34 51](https://cloud.githubusercontent.com/assets/6161338/8767464/174ddee4-2e5e-11e5-9d34-2cb8e8ff5943.png)

**Comment by dlech** [comment]
Got it. I usually use the Application Indicator plugin that shows the icon in the top notification tray instead of the GTK Tray Icon plugin that shows it in the bottom message tray. I think it should just be a matter of including a properly sized icon in the package. Right now, the only icon is 256x256 and it is scaled to fit (by GNOME, not the KeePass plugin).

**Comment by firtek** [comment]
Ok, I removed application indicator to try to get used to the "gnome way". Probably I'll get back to application indicator but I supposed it is good to report this.

**Comment by dlech** [comment]
I am not able to reproduce the bug. It shows in the small size for me (presumably 16x16).

![selection_042](https://cloud.githubusercontent.com/assets/963645/8767764/cc945102-2e2c-11e5-8da4-55a58ab1a791.png)

I've gone ahead an added more icons to the package anyway, so you can see if that makes a difference.

**Comment by dlech** [comment]
Give `keepass2-plugin-tray-icon` v0.1.1 a try (available in the beta ppa)

**Comment by firtek** [comment]
Now it is smaller, though looks a bit smaller than the rest but good enough I guess :)
![screenshot from 2015-07-19 23 00 32](https://cloud.githubusercontent.com/assets/6161338/8767843/06ae832a-2e6a-11e5-9696-78587a279af2.png)

**Comment by firtek** [comment]
This also fixed another problem. On left click and on right click I was getting the same menu. Now on left click it just opens keepass, two bugs in one run :+1:

**Comment by dlech** [comment]
You must have been using the application-indicator plugin before. It has the expected behavior to have the same action for left and right click. The tray-icon plugin has the more traditional behavior.

Also, I wonder if it needs a 24x24 icon. I just included 16x16 and 32x32 (and 48x48) because that is what was availible from the upstream keepass program.

**Comment by firtek** [comment]
It was indicator plugin, I didn't know about the diff. I think 24x24 would be better. If you update it I can send pic so you can decide.

**Comment by dlech** [comment]
I tried adding a 24x24 icon, but it did not make a difference. Also, when I manually updated my icon caches, I got the great big icon again. From what I can tell, the smaller icons are actually a bug. Or there is just inconsistent behavoir in GNOME. For example, I am showing a "removable devices" icon that is full sized too.

![selection_043](https://cloud.githubusercontent.com/assets/963645/8768009/5415a4c4-2e36-11e5-967c-674c294d8195.png)

**Comment by dlech** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=682242

**Comment by firtek** [comment]
I completely forgot that icon for removable devices was also big. So bug in gnome...

**Comment by dlech** [comment]
Yeah, after reading the GNOME bug, it sounds like the message tray was never designed for status icons like this anyway.
