### ISSUE TITLE
Kde 5 Application Indicator scroll actions and left click not working

### ISSUE THREAD

**Issue by scic** [dlech/Keebuntu#29]
I have the latest beta version of keepass2-plugin-application-indicator installed.
In Kde 5 only the right click on the tray icon seams to work. But in the description it is mentioned that a left click should open the menu as well and scroll up or down should maximize/minimize the application. These actions have no effect.
Could these actions be made to work for kde 5? Or could a short version for opening the main window be provided? e.g. the left click could tray and untray. That seams to be the standard behavior for the tray in kde anyway.

At the moment I can right click and select tray/untray but it is a little cumbersome.
I also tested the keepass2-plugin-tray-icon but this doesn't seem to work at all.

I have Kubuntu 15.04 with kubuntu-backports that has plasma 5.3.2 and frameworks 5.12. But it wasn't working with earlier plasma version either.
I have the libappindicator1 and  libappindicator3-1 default packages installed.

**Comment by dlech** [comment]
If KDE 5 does not implement application indicators or gtk tray icons correctly, there is nothing I can do about it.

If you want a truly KDE compatible tray icon, it sounds like we need to create a new plugin that uses [a Status Notifier](http://www.notmart.org/misc/statusnotifieritem/index.html).

**Comment by dlech** [comment]
There is now a proper plugin for Plasma/KDE5. See #37
