### ISSUE TITLE
KeebuntuAppIndicator.dll is not compatible with KeePass 2.30

### ISSUE THREAD

**Issue by shackra** [dlech/Keebuntu#30]
After launching KeePass, a dialog window shows up saying that such plugin isn't compatible with this current version of KeePass, 2.30.

**Comment by dlech** [comment]
Are you using the beta version from `ppa:dlech/keepass2-plugins-beta`?

**Comment by shackra** [comment]
I use a derivate distro from Arch Linux

**Comment by dlech** [comment]
You still need to say which version of the AppIndicator plugin you are using.

**Comment by shackra** [comment]
Oh, sorry. I compiled version 0.5.7

> El 11 de septiembre de 2015 a las 8:51 David Lechner
> <notifications@github.com> escribió:
> 
> 
> You still need to say which version of the AppIndicator plugin you are using.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dlech/Keebuntu/issues/30#issuecomment-139566048

--
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola
GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en
Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by dlech** [comment]
You are likely missing a dependency. You can run keepass2 with the `--debug` option to see if it will tell you more about the error.

**Comment by shackra** [comment]
Here:

![captura_12-09-2015-151609](https://cloud.githubusercontent.com/assets/1055216/9833764/718a5166-5961-11e5-91c9-a66da7598bcb.png)

I compiled the plugin inside a Chroot, why the compilation will success if a dependency was missing?

**Comment by shackra** [comment]
Ah, I see what I did wrong, I changed my `PKGBUILD` file and make libappindicator-sharp a dependency. Now I get this error:

![captura_12-09-2015-153533](https://cloud.githubusercontent.com/assets/1055216/9833918/119f8048-5964-11e5-8e52-ef69c15a0cb8.png)

and I see no tray icon of KeePass.

**Comment by dlech** [comment]
I just pushed a new version that will give a better error message.

https://github.com/dlech/Keebuntu/releases/tag/v0.5.8

**Comment by shackra** [comment]
Here:

![captura_12-09-2015-165625](https://cloud.githubusercontent.com/assets/1055216/9834234/3bf8847e-596f-11e5-9c24-0da6eeadb3b4.png)

**Comment by dlech** [comment]
so you are missing `libappindicator.so.1` it should come from the libappindicator-gtk2 package. If the name has changed, it needs to be fixed in the libappindicator-sharp package. There is nothing that can be done in Keebuntu.

**Comment by shackra** [comment]
It works now! Thank you!!

**Comment by dlech** [comment]
Excellent!
