### ISSUE TITLE
TrayTOTP plugin with keepass2-plugin-application-indicator on Linux Mint 17.2

### ISSUE THREAD

**Issue by mrclschstr** [dlech/Keebuntu#31]
Hi David,

I'm using the following software components:

* Linux Mint 17.2 64 bit
* Mono JIT compiler version 3.2.8
* Keepass 2.30 (from eugenesan PPA)
* KeepassHTTP 2.21 (from eugenesan PPA)
* keepass2-plugin-application-indicator 0.4.6

On my Windows computer I'm using the TrayTOTP plugin so I wanted to install it on my Linux laptop, too. But everytime I install the TrayTOTP plugin (2.0.0.5 from from eugenesan PPA) I get the following error message:

![image](https://cloud.githubusercontent.com/assets/6423849/11417478/d03c24c8-9417-11e5-88d0-4f6c1c7fa387.png)

I already tried the plugin from the official plugin homepage but that didn't work as well. I figured out that the application indicator is somehow the issue. When removing the app indicator plugin, TrayTOTP works fine despite the missing tray icon (which makes it really useless...).

I hope you can help me with my issue. When you need any further information, please let me know!

Kind regards

**Comment by dlech** [comment]
Does TrayTOTP have a source code repository?

I am pretty sure that the problem is that the Application Indicator plugin sets the Windows tray icon object to null and the TrayTOTP plugin is getting a null reference. 

Here is a patch I submitted to the KeePassHttp plugin to work around this. A similar fix could probably be applied to TrayTOTP.

https://github.com/pfn/keepasshttp/commit/c2f6110f1bee64fdc26565ea6c86ef0fbcd36396

**Comment by mrclschstr** [comment]
Seems like a good guess! They have a repository on Sourceforge: http://sourceforge.net/p/traytotp-kp2/code/

**Comment by dlech** [comment]
You should open an issue will the TrayTOTP plugin suggesting to replace all instances of `m_host.MainWindow.MainNotifyIcon.ContextMenuStrip` with `host.MainWindow.TrayContextMenu`. I think that should do the trick.

**Comment by mrclschstr** [comment]
Hi David,

I tried to fix this for myself by cloning the repository and replacing `m_host.MainWindow.MainNotifyIcon.ContextMenuStrip` as you suggested. Afterwards I created a PLGX file from the source code (http://keepass.info/help/v2_dev/plg_index.html#plgx). Unfortunately I get the same error message as before; it seems like this doesn't work.

Do you have another suggestion? Otherwise I'll open an issue but the TrayTOTP project doesn't seem that active any more. The last commit was in 2013.

**Comment by dlech** [comment]
OK. I think you have found a bug in the application indicator plugin. When I had a look at the TrayTOTP code, it uses events from `host.MainWindow.TrayContextMenu` that the application indicator may not be triggering. I'll have a look when I have a chance.

**Comment by mrclschstr** [comment]
I just checked the `keepass2-plugin-tray-icon` plugin and this has the same issue. Maybe it's a similar problem there as well?

**Comment by dlech** [comment]
Yes, most likely.

**Comment by dlech** [comment]
Fix has been released in  keepass2-plugin-ubuntu - 0.6.0

It is available in `ppa:dlech/keepass2-plugins-beta` for xenial only.

**Comment by dlech** [comment]
FYI, it still requires the fix to the TrayTOTP plugin from <https://github.com/dlech/Keebuntu/issues/31#issuecomment-161211052> too.
