### ISSUE TITLE
KeePass2 hangs opening db via http with either tray-icon or application-indicator

### ISSUE THREAD

**Issue by sgparry** [dlech/Keebuntu#33]
On kubuntu 15.04 (KDE), when either of the systray plugins is installed, KeePass2 fails to open databases via http or https. The program hangs and then eventually times out.

**Comment by dlech** [comment]
Which version of the plugins are you using? Do you have any other plugins installed?

**Comment by sgparry** [comment]
The versions I have been trying:
keepas2-plugin-application-indicator 0.4.7+0.5.7
-or-
keepass2-plugin-tray-icon 0.1.1+0.5.7 Konsole output

The other plug-ins I have:
Entry templates 6.0.1.0
KeePassRPC (For KeeFox) 1.5.4.0
KeeAgent 0.7.11.0

**Comment by sgparry** [comment]
Just confirming this is still a bug even after upgrading to Ubuntu 15.10 (KDE5).

**Comment by dlech** [comment]
I am not able to reproduce the issue.

Ubuntu 16.04
Plasma desktop (KDE)
KeePass 2.32

Plugins:
![selection_020](https://cloud.githubusercontent.com/assets/963645/14589748/3bba7b7a-04af-11e6-9fc6-8b2678bcb381.png)

Using `davserver -D ~ -u user -p pass` for webdav server (from `python-webdav` package).

**Comment by sgparry** [comment]
Which mono are you using? In my case it is the latest stable from the mono teams repos.

**Comment by dlech** [comment]
I'm using the official ubuntu package from 16.04 which should be very close to the same.

```
$ mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Comment by dlech** [comment]
Does this happen with the new Status Notifier plugin? See #37.

**Comment by dlech** [comment]
closing due to no response
