### ISSUE TITLE
KeePassHttp plugin dependencies list fix for deb package

### ISSUE THREAD

**Issue by synchrone** [dlech/Keebuntu#34]
`keepass2-plugin-keepasshttp` does not have any dependencies.

The correct list of dependencies looks like: 
```
libmono-system-xml-linq4.0-cil
libmono-system-data-datasetextensions4.0-cil
libmono-system-runtime-serialization4.0-cil
```
It can also work as a *.plgx file, windows-like, if `mono-mcs` wold be installed, but I see no reason to do that.

Also, the package bundles `
/usr/lib/keepass2/plugins/keepasshttp/Newtonsoft.Json.dll` file, which is wrong since it's available as a GAC binary via `libnewtonsoft-json5.0-cil`

**Comment by dlech** [comment]
My fork of KeePassHttp is actually [here](https://github.com/dlech/keepasshttp). Could you please open the issue there instead? (I had issues turned off there before for some reason. I turned them on, so if you tried before and there was not a place for issues, there will be now.)

**Comment by synchrone** [comment]
Thanks.
