### ISSUE TITLE
Add Mate to the list of supported desktops

### ISSUE THREAD

**Issue by Jojo144** [dlech/Keebuntu#36]
Hi,
Just to say that I tested `keepass2-plugin-tray-icon` and `keepass2-plugin-application-indicator` with Ubuntu Mate Vivid and both seem to work fine!
(At least, installation, minimization to tray and restoration.)
You could add Mate to the list of supported desktops  :-)

I could do deeper testing if you explain me what to do.

**Comment by dlech** [comment]
Thanks. I've added MATE to the readme. If you can click on a menu item and it does something, there really isn't any more testing to do.
