### ISSUE TITLE
StatusNotifierItem plugin for Plasma/KDE5

### ISSUE THREAD

**Issue by dlech** [dlech/Keebuntu#37]
Since 3 out of the 5 open issues here had to do with KDE, I decided that maybe I should make a KDE plugin. I've got it started in https://github.com/dlech/Keebuntu/commit/e6b764a96dca450e2424375cf4b40a3268417510. Since I'm not a KDE user, I'm going to need some help.
- What should the icon look like? Color/Mono? Different icons for different themes?
- I think we can show overlay icons (badges) on the icon, so for example we could have overlays for locked/unlocked. Ideas?
- What should the left-click behavior be? Right now it trays/untrays the application.
- What should the right-click behavior be? Presumably show a context menu. Given the way StatusNotifierItem is implemented, this will be tricky because we have to draw our own menu.
- What should the secondary-click (middle-click) behavior be, if any?
- What should the scroll behavior be, if any?

cc: @PAStheLoD, @scic, @sgparry

**Comment by dlech** [comment]
https://techbase.kde.org/Projects/Plasma/NewSystemTray

**Comment by scic** [comment]
Sounds great. Thanks for the effort.

I think the [KDE Visual Design Group (VDG)](https://forum.kde.org/viewforum.php?f=285) would help you with the icon. As I understand they might even create the needed icons for you. They might also help with behavior and overlays/badges.

For me just one monochrome stylized icon that fits with the standard ones would be great. But if you want to go the extra mile I would appreciate a visualization of the countdown for the "copy to the clipboard" action even more than the lock status (Maybe some progress circle around the icon). But I could see showing the lock status being a nice feature for others.

For me personally the left click should tray/untray and right click should display the context menu. No scroll action or middle click is needed.

**Comment by dlech** [comment]
https://github.com/KDE/plasma-workspace/blob/18740b7d4f62247ccdfddd4e1af5fa9e8b074be4/dataengines/statusnotifieritem/statusnotifieritemsource.cpp#L92

**Comment by dlech** [comment]
Initial version has been released in keepass2-plugin-ubuntu - 0.6.0

It is available in ppa:dlech/keepass2-plugins-beta for xenial only.

New package is `keepas2-plugin-status-notifier`. If you have `keepass2-plugin-application-indicator` or `keepass2-plugin-tray-icon` installed, you will need to uninstall it first.

**Comment by dlech** [comment]
Please open a new issue if you have any problems or suggestions.

**Comment by scic** [comment]
There is one issue with the new keepas2-plugin-status-notifier plugin:
If you untray keepass with a click on the tray icon and keep that window open, the other kde widgets in the system tray can no longer open their popup dialogs like calendar, klipper, networks etc. If you tray keepass again then the popup dialogs work again.

I'm on Kubuntu 16.04 with the default install of:
Plasma 5.5.5
Qt: 5.5.1
keepas2-plugin-status-notifier: 0.1.0+0.6.0

**Comment by dlech** [comment]
Perhaps you missed my request to please open a new issue for any problems? :wink: (It will probably get lost and forgotten otherwise.)
