### ISSUE TITLE
Move to new dependencies

### ISSUE THREAD

**Issue by frederikmoellers** [dlech/Keebuntu#42]
In Debian stretch (current testing release), both `libmagickwand-6.q16-2` and `libappindicator0.1` are no longer available. `libmagickwand` has been updated to `…-3` and `libappindicator` now is `libappindicator3`. I know that Keebuntu mainly targets Ubuntu, but I guess the changes will happen there as well in the near future.

I tried updating the dependencies myself, but the new version of `libappindicator` requires some less-than-trivial changes to the source code and I have no knowledge of both .NET and the library so I couldn't do it.

**Comment by frederikmoellers** [comment]
A workaround is to create a dummy package (e.g. with [equivs](https://www.debian.org/doc/manuals/apt-howto/ch-helpers.html)) which provides `libmagickwand-6.q16-2`. `libappindicator` can be installed from older versions of Debian with no dependency problems (as of now). If everything else is installed, the indicator works just fine (at least it does under XFCE).

**Comment by theonedemon** [comment]
UP

**Comment by dlech** [comment]
I've published a new package for zesty that should work for stretch. Please open a new issue if there is still a problem with libappindicator.
