### ISSUE TITLE
keepass2-plugin-ubuntu is not available for zesty

### ISSUE THREAD

**Issue by JonTheNiceGuy** [dlech/Keebuntu#43]
Hi,

I'm unable to use this package for Zesty. Is this for a reason? Is there anything I can do to help?

Thanks!

**Comment by dlech** [comment]
#42? Just haven't got around to looking into it yet.

**Comment by JonTheNiceGuy** [comment]
Ah, fair enough!

**Comment by pfoo** [comment]
Change libmagickwand-6.q16-2 -> libmagickwand-6.q16-3 in debian/control but that would break older versions of ubuntu

I'll go for ```libmagickwand-6.q16-2 | libmagickwand-6.q16-3```

**Comment by dlech** [comment]
@pfoo, I think it is slightly more complicated than this. I've got some time right now, so I will have a look.

**Comment by dlech** [comment]
Just published for 0.6.1 zesty.

**Comment by TheAntimist** [comment]
@dlech Thanks for the push, I tested it today and it works as expected on XUbuntu 17.04

**Comment by qalex** [comment]
works great!
