### ISSUE TITLE
Keepass Beta PPA repository is outdated

### ISSUE THREAD

**Issue by scic** [dlech/Keebuntu#45]
I have the problem that I need the beta repository for the keepass2-plugin-status-notifier but the  **keepassrpc** and  **keepasshttp** versions are newer in the non beta repository. Thus I can not use the new versions from the ppa.

I suggest to update the versions in the beta repository as well, so that the versions in the beta repository are equal to or newer than the ones from the stable repository.
Thus update the following packages in beta repository (with versions from stable repository):
- keefox
- keepasshttp
- keepassrpc

Furthermore I would suggest promoting at least:
-  keepass2-plugin-keeagent 0.9.1 from the beta channel to stable

And I would consider promoting the keepass2-plugin-ubuntu in beta to stable as well. They were released a long time ago as beta and at least the keepass2-plugin-status-notifier works well for me.

**Comment by dlech** [comment]
If you want the newest version of everything, you should use both PPAs at the same time.

**Comment by scic** [comment]
Thanks. I did not know that I could have both ppas simultaneously. The scenario described works for me now.
