### ISSUE TITLE
keepass2-plugin-application-indicator not working with XFCE

### ISSUE THREAD

**Issue by ghost** [dlech/Keebuntu#47]
I've got keepass installed, and keepass2-plugin-application-indicator, and not any other plugins or keepass indicators, and I can't get an tray icon for keepass. Perhaps the problem is my combination of keepass version and mono version; I've got a patched version of keepass and a beta of mono - for, without those tweaks I could not (at least on the Cinnamon setting I first tried keepass on) get autotype working.

**Comment by dlech** [comment]
I don't remember if XFCE prefers application indicators. Have you tried `keepass2-plugin-tray-icon` instead?

**Comment by oguzhanogreden** [comment]
@dlech, perhaps would save you some time if your dropped a note [here](https://superuser.com/a/814539) as the developer. I ended up pursuing the appindicator path due to that suggestion. keepass2-plugin-tray-icon works beautifully.
