### ISSUE TITLE
Debian Stretch libappindicator0.1-cil dependency problem

### ISSUE THREAD

**Issue by oguzhanogreden** [dlech/Keebuntu#48]
Hello!

I'm not sure if it is fair to make an issue regarding Debian support for a Ubuntu oriented PPA. In case you are interested, this is probably helpful.

Appindicator installation fails on Debian Stretch:
`keepass2-plugin-application-indicator : Depends: libappindicator0.1-cil but it is not installable`

Here seems to be the solution: https://github.com/duplicati/duplicati/issues/2157

Thanks for the great work!

**Comment by dlech** [comment]
This will probably be an issue for the next Ubuntu release as well. Thanks for looking into the issue. It should be easy enough to fix.

**Comment by dlech** [comment]
I have looked into this more and this requires migrating all of the extensions here to GTK 3. However, the mono winforms implementation uses GTK 2, so this is not technically possible at this point in time.

Which desktop environment do you use?

**Comment by mydexterid** [comment]
I don't want to hijack the issue, so please tell if I should open a new one instead.
Is this the cause why keepass2-plugin-application-indicator is not available for Ubuntu Bionic?

I'd like to use it in Bionic on gnome-flasback.

**Comment by dlech** [comment]
It looks like I missed copying that one to bionic. It should be available now.

However, since Ubuntu has dropped the Unity desktop, I think application indicators will be fading out in the coming years. I would suggest using the `keepass2-plugin-tray-icon` or `keepass2-plugin-status-notifier` plugin instead.

**Comment by dlech** [comment]
They are all part of `keepass2-plugin-ubuntu` shown in that list.

**Comment by dlech** [comment]
I'm dropping support of the application indicator since the Unity desktop has gone by the wayside. The Status Notifier icon should be a suitable replacement for most desktops.
