### ISSUE TITLE
keepass2-plugin-application-indicator not working on Gnome Shell 3.26

### ISSUE THREAD

**Issue by hackel** [dlech/Keebuntu#49]
I just upgraded to Ubuntu 17.10 beta 2, which features Gnome Shell 3.26.  This plugin unfortunately stopped working.  I've confirmed that KeePass is still loading it (version 0.4.9.0), but I don't get the actual icon anymore.  Ubuntu comes with https://github.com/ubuntu/gnome-shell-extension-appindicator by default now, which is the same extension I used before the upgrade, so it should be working as far as I know.

**Comment by dlech** [comment]
I have just tried this in bionic and the built-in shell extension does not seem to be working. I still had to install <https://extensions.gnome.org/extension/615/appindicator-support/>. Also, `keepass2-plugin-status-notifier` works with this extension.

**Comment by dlech** [comment]
Ubuntu 17.10 is end of life
