### ISSUE TITLE
keepass2-plugin-application-indicator prevents Kee from connecting to KeePass 2

### ISSUE THREAD

**Issue by gpuma** [dlech/Keebuntu#51]
I just did a fresh install of Linux Mint 18.3, KeePass2 and Kee on Firefox. Everything works fine except for the black icon (See Image 1). So I installed `keepass2-plugin-application-indicator` to fix this. However, once I installed them Kee cannot connect to KeePass2 anymore, this is the message:

_"You are not logged in to your password database. Launch KeePass to enable Kee"_

and Kee cannot connect (See Image 2). Once I uninstall the above plugin Kee can connect again.

Tested for both `keepass2-plugin-application-indicator` and `keepass2-plugin-tray-icon` (both regular and beta ppas) with the following:

- Linux Mint 18.3 Sylvia Cinnamon (64-bit) (based on Ubuntu 16.04)
- Firefox 57.0.1 64-bit
- Kee 2.0.0.25
- KeePass 2.37
- KeePassRPC 1.7.3.0

Image 1:
![funciona](https://user-images.githubusercontent.com/474235/34392124-44c844da-eb18-11e7-85bf-73199142ae15.png)

Image 2 (see the "off" Kee button):
![no-funciona](https://user-images.githubusercontent.com/474235/34392131-4dbb7ae4-eb18-11e7-8dda-8a594fd35fa9.png)

**Comment by AlbertSabalt** [comment]
KDE Neon 5.12 (64-bit) (based on Ubuntu 16.04)
KDE Plasma 5.12.1
Firefox 58.0.2
KeePass 2.38
KeePassRPC 1.7.3.0
Kee 2.1.26

Kee cannot connect to KeePass2 with keepass2-plugin-status-notifier

**Comment by dlech** [comment]
Are you installing KeePassRPC from the PPA as well?

    sudo apt install keepass2-plugin-rpc

**Comment by AlbertSabalt** [comment]
The plugin from the PPA version 1.7.0
Kee offers to update. No connection.
The KeeFox version of the PPA is not compatible with Firefox 58.

**Comment by dlech** [comment]
application-indicator plugin is no longer supported
