### ISSUE TITLE
Support for Debian 10 (Buster, Testing)

### ISSUE THREAD

**Issue by koutheir** [dlech/Keebuntu#52]
Please support installation on Debian 10 (Buster, currently Testing). Otherwise, please provide instructions to build the project on Debian, or hints for porting it.

**Comment by dlech** [comment]
I maintain too many things already, so I won't be providing a package for Buster.

Have you tried installing the Ubuntu packages on Debian? You can probably use the bionic ppa on buster.

**Comment by dlech** [comment]
Also see #48, there are technical issues preventing the application indicator plugin from working on Debian.

**Comment by chessmc** [comment]
Debian moved to newer versions of imagemagick in buster and sid, breaking keepass2-plugin-libimagemagick; Ubuntu is offering the same version as Debian sid in the cosmic proposed (main) repository.

buster has imagemagick 8:6.9.9.34+dfsg-3
sid  has imagemagick 8:6.9.10.2+dfsg-3

https://launchpad.net/ubuntu/+source/imagemagick
https://tracker.debian.org/pkg/imagemagick

**Comment by dlech** [comment]
hopefully the cosmic build from the beta ppa will work for buster, otherwise you can try building your own package https://github.com/dlech/Keebuntu/blob/master/doc/hacking.md
