### ISSUE TITLE
Can't minimize KeePass by clicking on icon

### ISSUE THREAD

**Issue by vertigo220** [dlech/Keebuntu#53]
This definitely works to (mostly) fix the tray icon in Mint Cinnamon 18.3, but while double-clicking the icon opens KeePass, as expected, double-clicking it again does _not_ minimize it like it does in Windows.

**Comment by dlech** [comment]
which plugin are you using?

**Comment by vertigo220** [comment]
Sorry, didn't even realize there was more than one associated with this page. It's GTKStatusIcon 0.1.1.0.

**Comment by dlech** [comment]
The "status notifier" plugin is designed to work with KDE. "Application indicators" are for the Ubuntu Unity desktop.

https://github.com/dlech/Keebuntu#status-notifier

**Comment by natrius** [comment]
Uhm, sorry, my fault. Working fine now :+1:
