### ISSUE TITLE
keepass2-plugin-launcher not working on elementaryOS Juno

### ISSUE THREAD

**Issue by weelillad** [dlech/Keebuntu#59]
Let me know if there's any further info I can provide.

## Versions

elementaryOS: 5.0 Juno, build on Ubuntu 18.04.2 LTS
plank: 0.11.4.24-0a84
keepass2-plugin-launcher: 0.1.2+0.6.1

## Expected behavior

Expecting to see options when right-clicking on the Keepass icon in the plank dock

## Actual behavior

(Keepass is already open with an unlocked database)
![Screenshot from 2019-04-16 18 41 16](https://user-images.githubusercontent.com/3506248/56203210-5d0cb780-6077-11e9-9bea-878dfae9c91a.png)

### Plugins folder

![Screenshot from 2019-04-16 18-43-51](https://user-images.githubusercontent.com/3506248/56203381-aeb54200-6077-11e9-8fbc-45415b79b1fa.png)

**Comment by dlech** [comment]
Try v0.1.2+0.7.0 from the beta ppa. https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins-beta

**Comment by weelillad** [comment]
Updated to v0.1.2+0.7.0 from the beta ppa, restarted my computer, still the same. If it makes any difference, my Keepass2 is version `2.41+dfsg-1~ubuntu18.04~ppa1` from https://launchpad.net/~jtaylor/+archive/ubuntu/keepass
