### ISSUE TITLE
Change blue icon

### ISSUE THREAD

**Issue by lonix1** [dlech/Keebuntu#61]
This shows a large blue icon, which is ugly in dark mode: `keepass2-plugin-status-notifier`.

Is it possible to change it, preferably to a smaller, dark-mode-friendly icon?

**Comment by dlech** [comment]
What desktop environment do you use? 

The plugin ships with a `breeze-dark` icon. https://github.com/dlech/Keebuntu/tree/bionic/StatusNotifierPlugin/Resources/icons

**Comment by lonix1** [comment]
latest of everything
ubuntu 19.04
gnome 3.32.2

I still have the blue icon, how do I switch to the dark one?

**Comment by lonix1** [comment]
@lucaszamboulis did you figure it out?

**Comment by dlech** [comment]
We probably need to copy the folder name from the old appindicator plugin

https://github.com/dlech/Keebuntu/tree/trusty/ApplicationIndicator/Resources/icons

**Comment by lonix1** [comment]
So that is something I must do to fix the issue in my system, or is that an issue in the code itself?

**Comment by dlech** [comment]
As a temporary workaround you should be able to copy the files or create symlinks. I don't know the rules for how themes decide which directory to use, but it has to do with finding the best matching file based on the directory names. There is nothing in the plugin code that says which directory to use.

**Comment by lonix1** [comment]
Okay thanks, I'll try that.

One last question, do you know where the icons are saved? I looked in `/usr/lib/keepass2/plugins/keebuntu` and `/usr/share/keepass2`.

I'll fiddle around to see how we can fix this (and report back here), but I'm not sure where it's saved.

**Comment by dlech** [comment]
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

**Comment by dlech** [comment]
something like `/usr/share/icons/...` IIRC

**Comment by lonix1** [comment]
Okay I found it.

The icons are installed to:
- `/usr/share/icons/breeze/status/22/keepass2-locked.svg`
- `/usr/share/icons/breeze-dark/status/22/keepass2-locked.svg`

However the "desktop" file `/usr/share/applications/keepass2.desktop` specifies to use an icon called `keepass2`.

And that is found in:
- `/usr/share/icons/hicolor/256x256/apps/keepass2-locked.png`
- `/usr/share/icons/hicolor/16x16/apps/keepass2-locked.png`
- `/usr/share/icons/hicolor/32x32/apps/keepass2-locked.png`
- `/usr/share/icons/hicolor/48x48/apps/keepass2-locked.png`

So it's linking to the wrong icon.

I tried replacing the blue icons with the breeze icons, but that didn't help. So I think the plugin's code is itself linking to the old blue icons, rather than the new breeze icons.

**Comment by dlech** [comment]
Here is what I did to make it work:

I saved the attached icon as `~/.local/share/icons/hicolor/16x16/apps/keepass2-locked.png`

Can't see it because it is white --> ![keepass2-locked](https://user-images.githubusercontent.com/963645/83959877-ae61a280-a847-11ea-9b97-cec5a4be0516.png)

[download](https://user-images.githubusercontent.com/963645/83959877-ae61a280-a847-11ea-9b97-cec5a4be0516.png)

**Comment by lonix1** [comment]
- I uninstalled the old version
- deleted any lingering keepass2 icons
- installed the new version
- did `sudo update-icon-caches /usr/share/icons/*`
- then applied your workaround, but I used this smaller icon: ![keepass2-locked](https://user-images.githubusercontent.com/40320097/83960953-d6c0bf80-a88e-11ea-9fd9-b26eaa6d9ef2.png) (the 16x16 icon in grayscale)

And now I have a dark-mode icon - thanks!

---
Consider mentioning this in the readme, I'm sure others will appreciate it too!

**Comment by Lantizia** [comment]
Hey I've noticed versions 0.8.0 and 0.8.1 are missing the breeze and breeze-dark SVG lock icons... 

So you end up being stuck with (at least on my MATE desktop) badly fitting blue-coloured PNGs, rather than a nice monochrome scalable icon.
