### ISSUE TITLE
Application indicator can't be installed in Ubuntu 19.04

### ISSUE THREAD

**Issue by iliaskomp** [dlech/Keebuntu#62]
Hi,
it seems like there is some dependency problem when installing keepass2-plugin-application-indicator in Ubuntu 19.04 (fresh installation)

When trying to `sudo apt install keepass2-plugin-application-indicator` I have the following error:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 keepass2-plugin-application-indicator : Depends: keepass2-plugin-libdbus (= 0.4.0+0.6.1) but it is not going to be installed
                                         Depends: keepass2-plugin-libimagemagick (= 0.2.9+0.6.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I have tried to use the beta repository but it seems that the application-indicator is not available.

Let me know if you need any more information!

**Comment by dlech** [comment]
Try `keepass2-plugin-status-notifier` instead.

**Comment by iliaskomp** [comment]
It can actually get installed and it works! Thank you!
