### ISSUE TITLE
Update README: ppa

### ISSUE THREAD

**Issue by robsdedude** [dlech/Keebuntu#65]
Your PPA mentioned in the README does not contain these plugins (anymore, I guess).

**Comment by robsdedude** [comment]
Let me correct that: keepass2-plugin-status-notifier does not exist. While keepass2-plugin-tray-icon does exist.

**Comment by dlech** [comment]
Which Linux distribution are you using?

**Comment by robsdedude** [comment]
Oh. Should've mentioned it. Linux mint 18. So `xenial` is what I've chosen.

**Comment by dlech** [comment]
It looks like it is in the beta ppa for xenial. https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins-beta
