### ISSUE TITLE
Fedora 31 - Gnome Shell - KeebuntuStatusNotifier - icon shown as 3 dots

### ISSUE THREAD

**Issue by mvrk69** [dlech/Keebuntu#67]
Hi,

Using the KeebuntuStatusNotifier plugin the keepass icon show as 3 dots:

![image](https://user-images.githubusercontent.com/3237472/77014684-29b36680-6973-11ea-99bd-287b955d4ad1.png)

Any idea what is the problem? How to fix?

**Comment by mvrk69** [comment]
appindicatorsupport@rgcjonas.gmail.com[3362500]: KeePass, Impossible to lookup icon for 'emblem-locked-panel'

**Comment by mvrk69** [comment]
No, so far i still have the problem.

**Comment by lonix1** [comment]
I had a similar problem before and managed to fix it [via this workaround](https://github.com/dlech/Keebuntu/issues/61). But it didn't work for me now on ubuntu, maybe it'll work for you on fedora.

**Comment by mvrk69** [comment]
I have the icons there:

ll /usr/share/icons/breeze/status/22/keepass*
-rw-r--r-- 1 root root 5310 Mar 19 11:55 /usr/share/icons/breeze/status/22/keepass2-locked.svg
lrwxrwxrwx 1 root root   19 Jun  5 10:37 /usr/share/icons/breeze/status/22/keepass2.svg -> keepass2-locked.svg

ll /usr/share/icons/breeze-dark/status/22/keepass*
-rw-r--r-- 1 root root 5356 Mar 19 11:55 /usr/share/icons/breeze-dark/status/22/keepass2-locked.svg
lrwxrwxrwx 1 root root   19 Jun  5 10:37 /usr/share/icons/breeze-dark/status/22/keepass2.svg -> keepass2-locked.svg

ll /usr/share/icons/hicolor/32x32/apps/keepass*
-rw-r--r-- 1 root root 1477 Mar 19 11:56 /usr/share/icons/hicolor/32x32/apps/keepass2-locked.png
-rw-r--r-- 1 root root 2238 Feb 29 11:08 /usr/share/icons/hicolor/32x32/apps/keepass.png

ll /usr/share/icons/hicolor/48x48/apps/keepass*
-rw-r--r-- 1 root root 2759 Mar 19 11:56 /usr/share/icons/hicolor/48x48/apps/keepass2-locked.png
-rw-r--r-- 1 root root 3448 Feb 29 11:08 /usr/share/icons/hicolor/48x48/apps/keepass.png

**Comment by lonix1** [comment]
Yeah exactly the same for me on ubuntu. Last time I discovered the plugin was looking in the wrong place and moved the icons around.

What I tried now was to copy the keepass icons into the "Yaru" directories which is the default icon set on ubuntu, but it didnt work.
